name: push action

on: 
  push:
    branches: ['main']

env:
  entry: ./src/data
  lngs: 'ar,fr,zh'

jobs:
  readAndSend:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: read jsons inn data
      id: files
      uses: ./read-json-action
      with: 
        entry: ${{env.entry}}
    - name: show result
      run: |
        echo ${{steps.files.outputs}}